package Vista;

import DTO.AlumnoDTO;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariel Eduardo Borbon Izaguirre ID:252116
 */
public class VistaGeneradorConstancia extends javax.swing.JFrame {

    private DefaultTableModel tableModel;

    /**
     * Creates new form VistaGeneradorConstancia
     */
    public VistaGeneradorConstancia() {
        initComponents();
        configurarComponentesAdicionales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaConstancia = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAlumnoABuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaAlumnos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdAlumnoEncontrado = new javax.swing.JTextField();
        txtNombreAlumnoEncontrado = new javax.swing.JTextField();
        txtCarreraAlumnoEncontrado = new javax.swing.JTextField();
        btnGenerarConstancia = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));

        textAreaConstancia.setEditable(false);
        textAreaConstancia.setColumns(20);
        textAreaConstancia.setRows(5);
        jScrollPane1.setViewportView(textAreaConstancia);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setText("Generar Constancia");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Introduce ID del Alumno:");

        txtIdAlumnoABuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Lista de alumnos:");

        tblListaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblListaAlumnos);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Alumno Seleccionado:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Nombre Completo:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("Carrera:");

        txtIdAlumnoEncontrado.setEditable(false);

        txtNombreAlumnoEncontrado.setEditable(false);

        txtCarreraAlumnoEncontrado.setEditable(false);

        btnGenerarConstancia.setBackground(new java.awt.Color(204, 255, 204));
        btnGenerarConstancia.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnGenerarConstancia.setText("Generar Constancia");
        btnGenerarConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarConstanciaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 156, 150));
        btnSalir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(97, 97, 97));
        jLabel8.setText("Doble click para seleccionar alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdAlumnoABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel8))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalir)
                            .addGap(92, 92, 92)
                            .addComponent(btnGenerarConstancia))
                        .addComponent(txtNombreAlumnoEncontrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(txtIdAlumnoEncontrado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCarreraAlumnoEncontrado, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdAlumnoABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdAlumnoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreAlumnoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarreraAlumnoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarConstancia)
                    .addComponent(btnSalir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConstanciaActionPerformed

    }//GEN-LAST:event_btnGenerarConstanciaActionPerformed

    
    
    /*
    Este metodo prepara la tabla en la que trabajaremos en la lista
    */
    private void configurarComponentesAdicionales() {
        String[] columnas = {"ID Alumno", "Nombre Completo", "Carrera"};
        this.tableModel = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblListaAlumnos.setModel(this.tableModel);
    }

    public String getIdBuscado() {
        return txtIdAlumnoABuscar.getText();
    }

    public String getIdAlumnoSeleccionado() {
        return txtIdAlumnoEncontrado.getText();
    }

    public String[] getDatosFilaSeleccionada() {
        int fila = tblListaAlumnos.getSelectedRow();
        if (fila != -1) {
            String id = tableModel.getValueAt(fila, 0).toString();
            String nombre = tableModel.getValueAt(fila, 1).toString();
            String carrera = tableModel.getValueAt(fila, 2).toString();
            return new String[]{id, nombre, carrera};
        }
        return null;
    }
    
    /*
    Nos traemos los alumnos y los colocamos en la tabla
    */

    public void mostrarAlumnosEnTabla(List<AlumnoDTO> alumnos) {
        tableModel.setRowCount(0);
        for (AlumnoDTO alumnoDTO : alumnos) { 
            Object[] fila = {
                alumnoDTO.getId(),
                alumnoDTO.getNombreCompleto(), 
                alumnoDTO.getCarrera()
            };
            tableModel.addRow(fila);
        }
    }

    
    
    /*
    LISTENERS PARA EL CONTROLADOR
    */
    
    
    
    public void mostrarAlumnoSeleccionado(String id, String nombre, String carrera) {
        txtIdAlumnoEncontrado.setText(id);
        txtNombreAlumnoEncontrado.setText(nombre);
        txtCarreraAlumnoEncontrado.setText(carrera);
    }

    public void mostrarConstancia(String contenido) {
        textAreaConstancia.setText(contenido);
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void addBuscarListener(DocumentListener listener) {
        txtIdAlumnoABuscar.getDocument().addDocumentListener(listener);
    }

    public void addSeleccionarAlumnoListener(MouseListener listener) {
        tblListaAlumnos.addMouseListener(listener);
    }

    public void addGenerarConstanciaListener(ActionListener listener) {
        btnGenerarConstancia.addActionListener(listener);
    }

    public void addSalirListener(ActionListener listener) {
        btnSalir.addActionListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarConstancia;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblListaAlumnos;
    private javax.swing.JTextArea textAreaConstancia;
    private javax.swing.JTextField txtCarreraAlumnoEncontrado;
    private javax.swing.JTextField txtIdAlumnoABuscar;
    private javax.swing.JTextField txtIdAlumnoEncontrado;
    private javax.swing.JTextField txtNombreAlumnoEncontrado;
    // End of variables declaration//GEN-END:variables
}
